baseURI: https://github.com/graphsense/graphsense-tagpacks/blob/develop
taxonomies:
  entity: https://interpol-innovation-centre.github.io/DW-VA-Taxonomy/assets/data/entities.csv
  abuse: https://interpol-innovation-centre.github.io/DW-VA-Taxonomy/assets/data/abuses.csv